### ISSUE TITLE
Cost pop-up shows up in the wrong place on Firefox Mobile 

### ISSUE THREAD

**Issue by Jassob** [JohanWinther/strecklista#5]
# What?
Clicking on your avatar on the web app in Firefox Beta for Android opens the "cost pop-up" in the top most part of the website (not in the viewport).
This does not happen on Chrome or other webkit-based browsers.

## Steps to reproduce
1. Use Firefox Beta. 
2. Click on your avatar in the web app. 
3. Scroll to the top of the page to see the pop up.

**TODO** add image.

I will try to debug and fix the issue when time arise.

**Comment by JohanWinther** [comment]
I am aware of this issue, however I plan on using the Polymer framework for the next version which should work on all devices.

**Comment by Jassob** [comment]
Right, then I'll not waste your or my time on fixing this issue then.

Great app!
