### ISSUE TITLE
Strecklista can't be accessed unless logged into the Google account that owns the sheet

### ISSUE THREAD

**Issue by elindgren** [JohanWinther/strecklista#7]
A created strecklista cannot be accessed unless logged into the Google account that owns the database sheet. This results in the app as showing an empty screen. See the attached picture. The webpage responds with a CORB error. See the attached picture of the webpage with the error.

This also happens to the strecklista-example that is linked in the readme. 

It doesn't matter if a user has editing rights to the database sheet. 

How to replicate (use either of the methods) - 

- Open a strecklista in inkognito mode
- log out of the owner's google account for the current session
-  Try to use a strecklista owned by someone else

![error_strecklista](https://user-images.githubusercontent.com/27208255/63651418-c2269700-c754-11e9-98db-28d687a6090c.png)

**Comment by JohanWinther** [comment]
I'll see tomorrow if it's possible to implement headers to allow the cross-origin request. I'm using the "jsonp" hack right now for the calls which is not really ideal anyway (really bad security-wise).

**Comment by JohanWinther** [comment]
Did some quick reading and this could be impossible to do since the headers need to be set on the servers i.e. Google's. So perhaps it's better to finish and migrate to the next version of the app.

Like I said, I'll have to check it out tomorrow.

**Comment by JohanWinther** [comment]
The reason the example didn't work was because I accidentally removed the permission for the Google Apps script to access my account a while back. It should be working now.

I can't seem to be able to replicate your issue. What shows up if you access the link in the error message manually?

Version: Firefox 68.0.2

**Comment by elindgren** [comment]
I checked on my end and I had a permission error as well. I thought that it was something more complicated since your example didn't work, but now it works fine. Thank you for your quick response and help. :)

**Comment by elindgren** [comment]
Can't seem to mark issue as resolved.

**Comment by JohanWinther** [comment]
It is resolved when it's "Closed".
